# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: |
    dotnet pack -c Release src/Avalonia.Markup.Declarative/Avalonia.Markup.Declarative.csproj
  displayName: 'Build and Package'
