using System;
using Avalonia.Data;
using Avalonia.Data.Converters;

namespace Avalonia.Markup.Declarative;

public static class ComponentExtensions
{
    /// <summary>
    /// Used by autogenerated extensions from source generator for direct apply value to component's property
    /// </summary>
    /// <typeparam name="TControl"></typeparam>
    /// <param name="control"></param>
    /// <param name="sourcePropertyPathString"></param>
    /// <param name="setAction"></param>
    /// <param name="bindingMode"></param>
    /// <param name="converter"></param>
    /// <param name="bindingSource"></param>
    /// <returns></returns>
    public static TControl _setCommonEx<TControl>(this TControl control, string? sourcePropertyPathString, Action setAction,
        BindingMode? bindingMode, IValueConverter? converter, object? bindingSource)
        where TControl : AvaloniaObject
    {
        setAction();
        if (control is IMvuComponent viewBase)
            viewBase.UpdateState();
        return control;
    }
}